name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: dist/client
          clean: true
          single-commit: true
          clean-exclude: |
            .nojekyll
